version: '3.8'

services:
  frontend:
    image: ${FRONTEND_IMAGE:-mentorai/frontend:latest}
    restart: always
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend
    networks:
      - mentorai-network

  backend:
    image: ${BACKEND_IMAGE:-mentorai/backend:latest}
    restart: always
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-mentorai}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - APP_ENV=${APP_ENV:-production}
    depends_on:
      - postgres
    volumes:
      - backend-uploads:/app/uploads
    networks:
      - mentorai-network

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-mentorai}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mentorai-network

volumes:
  postgres-data:
  backend-uploads:

networks:
  mentorai-network:
    driver: bridge 