version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    environment:
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=mentoruser
      - DB_PASSWORD=mentoruserpassword
      - DB_NAME=mentordb
      - JWT_SECRET=changethissecretinproduction
      - ENVIRONMENT=development
    volumes:
      - backend_uploads:/app/uploads
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - mentor_network

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mentor_network

  # Database service
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=mentoruser
      - POSTGRES_PASSWORD=mentoruserpassword
      - POSTGRES_DB=mentordb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mentor_network

# Define networks
networks:
  mentor_network:
    driver: bridge

# Define volumes
volumes:
  postgres_data:
    driver: local
  backend_uploads:
    driver: local 